# Generated by Django 3.0.4 on 2020-03-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200329_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SCategory',
            new_name='Sategory',
        ),
    ]
