# Generated by Django 3.0.4 on 2020-03-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200329_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sategory',
            options={'ordering': ('name',), 'verbose_name': 'sategory', 'verbose_name_plural': 'sategories'},
        ),
    ]
